CXX=g++
RM=rm -f
LIBS = -lglut -lGL
INCDIRS = -I../../includes
CXXFLAGS=-Wall -g $(INCDIRS)
BINDIR=../../bin

SRCS=ex1.cpp
OBJS=$(subst .cpp,.o,$(SRCS))
BIN = ex1

all: $(BIN)

$(BIN): $(OBJS)
	$(CXX)  -o $(BIN) $(OBJS) $(LIBS) $(CXXFLAGS) libGLEW.a

install: $(BIN)
	mv $(BIN) $(BINDIR)/$(BIN)

clean:
	$(RM) $(OBJS);\
	$(RM) $(BIN);

distclean: clean
	$(RM) $(BINDIR)/$(BIN)
