SHELL = /bin/sh
PLAT = linux

all:
	make -f Makefile.$(PLAT)

install:
	make -f Makefile.$(PLAT) install

clean:
	make -f Makefile.$(PLAT) clean

distclean: clean
	make -f Makefile.$(PLAT) distclean;
