CXX=g++
RM=rm -f
LIBS = -lglut -lGL -lGLEW
CXXFLAGS=
BINDIR=../../bin

SRCS=ex1.cpp
OBJS=$(subst .cpp,.o,$(SRCS))
BIN = ex1

all: $(BIN)

$(BIN): $(OBJS)
	$(CXX)  -o $(BIN) $(OBJS) $(LIBS) $(CXXFLAGS)

install: $(BIN)
	mv $(BIN) $(BINDIR)/$(BIN)

clean:
	$(RM) $(OBJS);\
	$(RM) $(BIN);

distclean: clean
	$(RM) $(BINDIR)/$(BIN)


