CXX=g++
RM=rm -f
INCDIRS = -I../../includes
LIBS = -framework GLUT -framework OpenGL
CXXFLAGS=-Wno-deprecated $(INCDIRS)
BINDIR=../../bin
SRCS=ex8.cpp
OBJS=$(subst .cpp,.o,$(SRCS))
BIN = ex8

all: $(BIN)

$(BIN): $(OBJS)
	$(CXX)  -o $(BIN) $(OBJS) $(INCDIRS) $(LIBS) $(CXXFLAGS)

install: $(BIN)
	mv $(BIN) $(BINDIR)

clean:
	$(RM) $(OBJS);\
	$(RM) $(BIN);

distclean: clean
	$(RM) $(BINDIR)/$(BIN)

