CXX=g++
RM=rm -f
LIBS = -framework GLUT -framework OpenGL
CXXFLAGS=-Wno-deprecated
BINDIR=../../bin

SRCS=hello.cpp
OBJS=$(subst .cpp,.o,$(SRCS))
BIN = hello

all: $(BIN)

$(BIN): $(OBJS)
	$(CXX)  -o $(BIN) $(OBJS) $(LIBS) $(CXXFLAGS)

install: $(BIN)
	mv $(BIN) $(BINDIR)

clean:
	$(RM) $(OBJS)

distclean: clean
	$(RM) $(BINDIR)/$(BIN)

