CXX=g++
RM=rm -f
LIBS = -lglut -lGL
CXXFLAGS=
BINDIR=../../bin

SRCS=hello.cpp
OBJS=$(subst .cpp,.o,$(SRCS))
BIN = hello

all: $(BIN)

$(BIN): $(OBJS)
	$(CXX)  -o $(BIN) $(OBJS) $(LIBS) $(CXXFLAGS)

install: $(BIN)
	mv $(BIN) $(BINDIR)/$(BIN)

clean:
	$(RM) $(OBJS);\
	$(RM) $(BIN);

distclean: clean
	$(RM) $(BINDIR)/$(BIN)

